package main

import (
	_ "github.com/videonext/onvif/profiles/accesscontrol"
	_ "github.com/videonext/onvif/profiles/accessrules"
	_ "github.com/videonext/onvif/profiles/advancedsecurity"
	_ "github.com/videonext/onvif/profiles/analytics"
	_ "github.com/videonext/onvif/profiles/authenticationbehavior"
	_ "github.com/videonext/onvif/profiles/credential"
	_ "github.com/videonext/onvif/profiles/device"
	_ "github.com/videonext/onvif/profiles/deviceio"
	_ "github.com/videonext/onvif/profiles/display"
	_ "github.com/videonext/onvif/profiles/doorcontrol"
	_ "github.com/videonext/onvif/profiles/event"
	_ "github.com/videonext/onvif/profiles/imaging"
	_ "github.com/videonext/onvif/profiles/media"
	_ "github.com/videonext/onvif/profiles/media2"
	_ "github.com/videonext/onvif/profiles/provisioning"
	_ "github.com/videonext/onvif/profiles/ptz"
	_ "github.com/videonext/onvif/profiles/receiver"
	_ "github.com/videonext/onvif/profiles/recording"
	_ "github.com/videonext/onvif/profiles/replay"
	_ "github.com/videonext/onvif/profiles/schedule"
	_ "github.com/videonext/onvif/profiles/search"
	_ "github.com/videonext/onvif/profiles/thermal"
	_ "github.com/videonext/onvif/profiles/uplink"
)
